FROM ruby:<%= version %>

<%= File.read "debian-prelude.step" %>

<%= File.read "debian-valgrind.step" %>

<%= File.read "debian-libxml-et-al.step" %>

<%= File.read "update-bundler.step" %>

<%= File.read "bundle-install.step" %>
