# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      development-dependencies:
        dependency-type: "development"
    cooldown:
      semver-major-days: 7
      semver-minor-days: 3
      semver-patch-days: 2
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
