# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "racc", "~>1.4"
gem "mini_portile2", "~>2.5.0"

gem "concourse", "~>0.40", :group => [:development, :test]
gem "hoe", "~>3.22", ">=3.22.1", :group => [:development, :test]
gem "hoe-bundler", "~>1.2", :group => [:development, :test]
gem "hoe-debugging", "~>2.0", :group => [:development, :test]
gem "hoe-gemspec", "~>1.0", :group => [:development, :test]
gem "hoe-git", "~>1.6", :group => [:development, :test]
gem "hoe-markdown", "~>1.1", :group => [:development, :test]
gem "minitest", "~>5.8", :group => [:development, :test]
gem "minitest-reporters", "~>1.4", :group => [:development, :test]
gem "rake", "~>13.0", :group => [:development, :test]
gem "rake-compiler", "~>1.1", :group => [:development, :test]
gem "rake-compiler-dock", "~>1.0", :group => [:development, :test]
gem "rexical", "~>1.0.5", :group => [:development, :test]
gem "rubocop", "~>0.88", :group => [:development, :test]
gem "simplecov", "~>0.17.0", :group => [:development, :test]
gem "rdoc", ">=4.0", "<7", :group => [:development, :test]

# vim: syntax=ruby
