# this is a generated file, to avoid over-writing it just delete this comment
begin
  require 'jar_dependencies'
rescue LoadError
  require 'commons-codec/commons-codec/1.15/commons-codec-1.15.jar'
  require 'net/sourceforge/htmlunit/neko-htmlunit/2.63.0/neko-htmlunit-2.63.0.jar'
  require 'com/fasterxml/woodstox/woodstox-core/6.2.6/woodstox-core-6.2.6.jar'
  require 'xerces/xercesImpl/2.12.2/xercesImpl-2.12.2.jar'
  require 'org/apache/santuario/xmlsec/2.3.1/xmlsec-2.3.1.jar'
  require 'xalan/serializer/2.7.2/serializer-2.7.2.jar'
  require 'isorelax/isorelax/20030108/isorelax-20030108.jar'
  require 'org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar'
  require 'xalan/xalan/2.7.2/xalan-2.7.2.jar'
  require 'org/codehaus/woodstox/stax2-api/4.2.1/stax2-api-4.2.1.jar'
  require 'nu/validator/jing/20200702VNU/jing-20200702VNU.jar'
  require 'org/nokogiri/nekodtd/0.1.11.noko1/nekodtd-0.1.11.noko1.jar'
  require 'net/sf/saxon/Saxon-HE/9.6.0-4/Saxon-HE-9.6.0-4.jar'
  require 'jakarta/xml/bind/jakarta.xml.bind-api/2.3.3/jakarta.xml.bind-api-2.3.3.jar'
  require 'xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar'
  require 'jakarta/activation/jakarta.activation-api/1.2.2/jakarta.activation-api-1.2.2.jar'
end

if defined? Jars
  require_jar 'commons-codec', 'commons-codec', '1.15'
  require_jar 'net.sourceforge.htmlunit', 'neko-htmlunit', '2.63.0'
  require_jar 'com.fasterxml.woodstox', 'woodstox-core', '6.2.6'
  require_jar 'xerces', 'xercesImpl', '2.12.2'
  require_jar 'org.apache.santuario', 'xmlsec', '2.3.1'
  require_jar 'xalan', 'serializer', '2.7.2'
  require_jar 'isorelax', 'isorelax', '20030108'
  require_jar 'org.slf4j', 'slf4j-api', '1.7.36'
  require_jar 'xalan', 'xalan', '2.7.2'
  require_jar 'org.codehaus.woodstox', 'stax2-api', '4.2.1'
  require_jar 'nu.validator', 'jing', '20200702VNU'
  require_jar 'org.nokogiri', 'nekodtd', '0.1.11.noko1'
  require_jar 'net.sf.saxon', 'Saxon-HE', '9.6.0-4'
  require_jar 'jakarta.xml.bind', 'jakarta.xml.bind-api', '2.3.3'
  require_jar 'xml-apis', 'xml-apis', '1.4.01'
  require_jar 'jakarta.activation', 'jakarta.activation-api', '1.2.2'
end

# generated by the :vendor_jars rake task
module Nokogiri
  JAR_DEPENDENCIES = {
    "com.fasterxml.woodstox:woodstox-core" => "6.2.6",
    "commons-codec:commons-codec" => "1.15",
    "isorelax:isorelax" => "20030108",
    "jakarta.activation:jakarta.activation-api" => "1.2.2",
    "jakarta.xml.bind:jakarta.xml.bind-api" => "2.3.3",
    "net.sf.saxon:Saxon-HE" => "9.6.0-4",
    "net.sourceforge.htmlunit:neko-htmlunit" => "2.63.0",
    "nu.validator:jing" => "20200702VNU",
    "org.apache.santuario:xmlsec" => "2.3.1",
    "org.codehaus.woodstox:stax2-api" => "4.2.1",
    "org.nokogiri:nekodtd" => "0.1.11.noko1",
    "org.slf4j:slf4j-api" => "1.7.36",
    "xalan:serializer" => "2.7.2",
    "xalan:xalan" => "2.7.2",
    "xerces:xercesImpl" => "2.12.2",
    "xml-apis:xml-apis" => "1.4.01",
  }.freeze
  XERCES_VERSION = JAR_DEPENDENCIES["xerces:xercesImpl"]
  NEKO_VERSION = JAR_DEPENDENCIES["net.sourceforge.htmlunit:neko-htmlunit"]
end
