#! /usr/bin/env bash

# for inspiration / related cross-ruby building, see:
# - https://github.com/rake-compiler/rake-compiler/blob/master/tasks/bin/cross-ruby.rake
# - https://github.com/apolcyn/grpc/blob/master/tools/distrib/build_ruby_environment_macos.sh

# see test/test_gem_platform.rb for context
gem_platform_name="x86_64-darwin"

# chosen so chruby will see it, should you be a user of chruby
RUBIES_DIR=${HOME}/.rubies

# prerequisites on OSX
if [[ -z "$(which ruby-install)" ]] ; then
  echo "ERROR: ruby-install is not installed, please install it: https://github.com/postmodern/ruby-install"
  exit 1
fi

set -o errexit
set -o pipefail

CROSS_FILE=".cross_rubies"
RUBIES=$(cat $CROSS_FILE | fgrep darwin | cut -d. -f1,2 | sort -u)

RAKE_COMPILER_CONFIG_DIR=${HOME}/.rake-compiler
RAKE_COMPILER_CONFIG=${RAKE_COMPILER_CONFIG_DIR}/config.yml
TMP_CONFIG=$(mktemp /tmp/rake-compiler-config.XXXXXXXX)

echo "---" > $TMP_CONFIG

for ruby in $RUBIES ; do
  ruby_fullname="native-builder-${ruby}"
  ruby_minor="${ruby}.0"

  rbconfig=$(echo ${RUBIES_DIR}/${ruby_fullname}/lib/ruby/${ruby_minor}/*/rbconfig.rb)
  if [[ ! -e $rbconfig ]] ; then
    echo "installing $ruby_fullname ..."
    ruby-install -i ${RUBIES_DIR}/${ruby_fullname} ruby ${ruby} \
                 -- \
                 --enable-static \
                 --disable-shared \
                 --without-gmp \
                 --disable-install-doc
    rbconfig=$(echo $rbconfig)
  else
    echo "ruby $ruby_fullname is installed"
  fi

  echo "rbconfig-${gem_platform_name}-${ruby_minor}: \"${rbconfig}\"" >> $TMP_CONFIG
done

mkdir -p $RAKE_COMPILER_CONFIG_DIR
cp $TMP_CONFIG $RAKE_COMPILER_CONFIG
cat $RAKE_COMPILER_CONFIG
