#! /usr/bin/env bash
#
#  run as part of CI, see gem-install.yml
#
if [[ $# -lt 2 ]] ; then
  echo "usage: $(basename $0) <output_dir> <platform>"
  exit 1
fi

OUTPUT_DIR=$1
BUILD_NATIVE_GEM=$2

test -e /etc/os-release && cat /etc/os-release

if [[ "${BUILD_NATIVE_GEM}" != "ruby" ]] ; then
  # normally part of rake-compiler-dock runas which we can't easily use in concourse
  . /etc/rubybashrc
  ln -s /usr/local/rake-compiler "$HOME"/.rake-compiler
  export RAKE_EXTENSION_TASK_NO_NATIVE=true
fi

set -e -x -u

bundle install --local || bundle install
bundle exec rake set-version-to-timestamp

if [[ "${BUILD_NATIVE_GEM}" == "ruby" ]] ; then
  # TODO we're only compiling so that we retrieve libxml2/libxslt tarballs, we can do better.
  bundle exec rake clean compile
  bundle exec rake gem
else
  bundle exec rake gem:${BUILD_NATIVE_GEM}:builder FORCE_CROSS_COMPILING=true
fi

./scripts/test-gem-file-contents pkg/nokogiri*.gem

mkdir -p ${OUTPUT_DIR}
cp -v pkg/nokogiri*.gem ${OUTPUT_DIR}
ls -l ${OUTPUT_DIR}/*
