#! /usr/bin/env bash
#
#  run as part of CI, see gem-install.yml
#
if [[ $# -lt 1 ]] ; then
  echo "usage: $(basename $0) <gems_dir> [install_flags]"
  exit 1
fi

GEMS_DIR=$1
shift
INSTALL_FLAGS=$*

test -e /etc/os-release && cat /etc/os-release

set -e -x -u

pushd $GEMS_DIR

  gemfile=$(ls *.gem | head -n1)
  ls -l ${gemfile}
  gem install --no-document ${gemfile} -- ${INSTALL_FLAGS}
  gem list -d nokogiri
  nokogiri -v

popd

# 2.3.21 because https://github.com/rubygems/rubygems/issues/5914
# 2.3.22 because https://github.com/rubygems/rubygems/issues/5940
gem install bundler -v "~> 2.2, != 2.3.21, != 2.3.22"
bundle config set --local without rdoc
bundle install --local || bundle install

rm -rf lib ext # ensure we don't use the local files
rake test

./scripts/test-gem-installation
