% require "common_prelude.rb"

resource_types:
<%= erbify_file "common_resource_types.yml" -%>


resources:
<%= erbify_file "common_resources.yml" -%>
  - name: nokogiri
    type: git
    icon: "github-circle"
    source:
      uri: https://github.com/sparklemotion/nokogiri/
      branch: "v1.10.x"
      ignore_paths: <%= $common_ignore_paths %>


anchors:
<%= erbify_file "common_anchors.yml" -%>


jobs:
% RUBIES[:mri].each do |ruby_version|
  - name: ruby-<%= ruby_version %>-system
    public: true
    serial_groups: ["ruby-<%= ruby_version %>"]
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: "flavorjones/nokogiri-test", tag: "mri-<%= ruby_version %>"}
          inputs:
            - name: ci
            - name: nokogiri
          params:
            NOKOGIRI_USE_SYSTEM_LIBRARIES: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
% if Concourse.production_rubies.include? ruby_version
        on_failure: *notify_failure_to_irc
% end

  - name: ruby-<%= ruby_version %>-vendored
    public: true
    serial_groups: ["ruby-<%= ruby_version %>"]
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
        passed: ["ruby-<%= ruby_version %>-system"]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: "flavorjones/nokogiri-test", tag: "mri-<%= ruby_version %>"}
          inputs:
            - name: ci
            - name: nokogiri
          run:
            path: ci/concourse/tasks/rake-test/run.sh
% if Concourse.production_rubies.include? ruby_version
        on_failure: *notify_failure_to_irc
% end

  - name: ruby-<%= ruby_version %>-valgrind
    public: true
    serial_groups: ["ruby-<%= ruby_version %>"]
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
        passed: ["ruby-<%= ruby_version %>-vendored"]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: "flavorjones/nokogiri-test", tag: "mri-<%= ruby_version %>"}
          inputs:
            - name: ci
            - name: nokogiri
          params:
            TEST_WITH_VALGRIND: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
% if Concourse.production_rubies.include? ruby_version
        on_failure: *notify_failure_to_irc
% end
% end


% RUBIES[:jruby].each_with_index do |jruby_version, j|
  - name: jruby-<%= jruby_version %>
    public: true
    serial_groups: ["jruby"]
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
% if j > 0
        passed: ["jruby-<%= RUBIES[:jruby][j-1] %>"]
% end
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: "flavorjones/nokogiri-test", tag: "jruby-<%= jruby_version %>"}
          inputs:
            - name: ci
            - name: nokogiri
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: *notify_failure_to_irc
% end


  - name: gate
    public: true
    plan:
      - get: nokogiri
        trigger: true
        passed:
% Concourse.production_rubies.each do |ruby_version|
          - "ruby-<%= ruby_version %>-valgrind"
% end
          - "jruby-<%= RUBIES[:jruby].last %>"


  - name: ruby-vanilla-system
    public: true
    serial: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
        passed: ["gate"]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: "flavorjones/nokogiri-test", tag: xenial}
          inputs:
            - name: ci
            - name: nokogiri
          params:
            NOKOGIRI_USE_SYSTEM_LIBRARIES: t
            TEST_WITH_APT_REPO_RUBY: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: *notify_failure_to_irc


  - name: ruby-libxmlruby-system
    public: true
    serial: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
        passed: ["gate"]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: "flavorjones/nokogiri-test", tag: "mri-<%= Concourse.production_rubies.last %>"}
          inputs:
            - name: ci
            - name: nokogiri
          params:
            BUNDLE_GEMFILE: "Gemfile-libxml-ruby"
            NOKOGIRI_USE_SYSTEM_LIBRARIES: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: *notify_failure_to_irc


  - name: ruby-libxmlruby-valgrind
    public: true
    serial: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
        passed: ["gate"]
      - task: rake-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: "flavorjones/nokogiri-test", tag: "mri-<%= Concourse.production_rubies.last %>"}
          inputs:
            - name: ci
            - name: nokogiri
          params:
            BUNDLE_GEMFILE: "Gemfile-libxml-ruby"
            TEST_WITH_VALGRIND: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
        on_failure: *notify_failure_to_irc


  - name: gem-test
    public: true
    serial: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
        passed: ["gate"]
      - task: gem-build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: "flavorjones/nokogiri-test", tag: "mri-<%= Concourse.production_rubies.last %>"}
          inputs:
            - name: ci
            - name: nokogiri
          outputs:
            - name: gems
          run:
            path: ci/concourse/tasks/gem-test/gem-build.sh
        on_failure: *notify_failure_to_irc
      - task: gem-install-and-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: "flavorjones/nokogiri-test", tag: "mri-<%= Concourse.production_rubies.last %>"}
          inputs:
            - name: ci
            - name: nokogiri
            - name: gems
          run:
            path: ci/concourse/tasks/gem-test/gem-install-and-test.sh
        on_failure: *notify_failure_to_irc

  - name: gem-test-java
    public: true
    serial: true
    plan:
      - get: ci
      - get: nokogiri
        trigger: true
        passed: ["gate"]
      - task: gem-build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: "flavorjones/nokogiri-test", tag: "jruby-<%= RUBIES[:jruby].last %>"}
          inputs:
            - name: ci
            - name: nokogiri
          outputs:
            - name: gems
          run:
            path: ci/concourse/tasks/gem-test/gem-build-java.sh
        on_failure: *notify_failure_to_irc
      - task: gem-install-and-test
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: "flavorjones/nokogiri-test", tag: "jruby-<%= RUBIES[:jruby].last %>"}
          inputs:
            - name: ci
            - name: nokogiri
            - name: gems
          run:
            path: ci/concourse/tasks/gem-test/gem-install-and-test.sh
        on_failure: *notify_failure_to_irc


  - name: build-success
    public: true
    disable_manual_trigger: true
    plan:
      - get: nokogiri
        trigger: true
        version: every
        passed:
          - ruby-vanilla-system
          - ruby-libxmlruby-system
          - ruby-libxmlruby-valgrind
          - gem-test
          - gem-test-java
      - put: nokogiri-irc
        params: {message: "($BUILD_PIPELINE_NAME/$BUILD_JOB_NAME) The build passed ($BUILD_URL)"}
