require 'jar_dependencies'
JBUNDLER_LOCAL_REPO = Jars.home
JBUNDLER_JRUBY_CLASSPATH = []
JBUNDLER_JRUBY_CLASSPATH.freeze
JBUNDLER_TEST_CLASSPATH = []
JBUNDLER_TEST_CLASSPATH.freeze
JBUNDLER_CLASSPATH = []
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/xerces/xercesImpl/2.12.0/xercesImpl-2.12.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar')
JBUNDLER_CLASSPATH.freeze
